version: '3.4'
services:
  r_base:
    image: dockerplumber
    # image: fdrennan/environ:beta
    # image: fdrennan/environ:dev
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    restart: always
    environment:
      R_TEST: testing
    volumes:
      - ./app.R:/app.R
      - ./main.R:/main.R
    user: 'root'
    ports:
      - "80:3000"
    command: ["Rscript", "/main.R"]

volumes:
  shiny_logs:
